public class Main {
    private static AllVehicles vp = new AllVehicles();
    private static AllRoutes ar = new AllRoutes();
    private static AllStops as = new AllStops();
    private static AllEmployees ae = new AllEmployees();

    private static Depot d1 = new Depot("Bucium", 30);
    private static Depot d2 = new Depot("Unirii", 210);
    private static Depot d3 = new Depot("Zorilor", 120);

    private static Route r1 = new Route(35);
    private static Route r2 = new Route(40);

    public static void main(String[] args) {
        as.addStop(new Stop("Taberei"));
        as.addStop(new Stop("Calea Floresti"));
        as.addStop(new Stop("Nodul N"));
        as.addStop(new Stop("VIVO"));
        as.addStop(new Stop("Ciobanului"));
        as.addStop(new Stop("P-ta Flora"));
        as.addStop(new Stop("Calea Manastur"));
        as.addStop(new Stop("Agronomia"));
        as.addStop(new Stop("Calea Motilor"));
        as.addStop(new Stop("Memorandumului Sud"));
        as.addStop(new Stop("Victoria"));
        as.addStop(new Stop("Regionala CFR"));
        as.addStop(new Stop("Biserica Sf. Petru"));
        as.addStop(new Stop("P-ta Marasti"));
        as.addStop(new Stop("Maresal C-tin Prezan"));
        as.addStop(new Stop("Dorobantilor"));
        as.addStop(new Stop("Campus Universitar Vest"));
        as.addStop(new Stop("Iulius Mall Vest"));
        as.addStop(new Stop("Valeriu Bologa"));
        as.addStop(new Stop("Colegiul Pedagogic"));
        as.addStop(new Stop("Iulius Mall Est"));
        as.addStop(new Stop("Campus Universitar Est"));
        as.addStop(new Stop("Arte Plastice"));
        as.addStop(new Stop("Crinului"));
        as.addStop(new Stop("Somes"));
        as.addStop(new Stop("Constanta"));
        as.addStop(new Stop("Sora"));
        as.addStop(new Stop("Memorandumului Nord"));
        as.addStop(new Stop("Spitalul de Copii"));
        as.addStop(new Stop("Fabrica de Bere"));
        as.addStop(new Stop("Gradini Manastur"));

        as.addStop(new Stop("Central"));
        as.addStop(new Stop("Closca"));
        as.addStop(new Stop("P-ta Garii"));
        as.addStop(new Stop("Traian"));
        as.addStop(new Stop("P-ta Mihai Viteazul"));

        as.addStop(new Stop("Biblioteca Judeteana"));
        as.addStop(new Stop("Sc. S. Barnutiu"));
        as.addStop(new Stop("Tribunal"));
        as.addStop(new Stop("P-ta Avram Iancu"));

        as.addStop(new Stop("P-ta Cipariu"));
        as.addStop(new Stop("Gheorghe Doja"));
        as.addStop(new Stop("Calea Turzii"));
        as.addStop(new Stop("W.A. Mozart"));
        as.addStop(new Stop("Electrogroup"));
        as.addStop(new Stop("Compexit"));
        as.addStop(new Stop("Dacia Service"));
        as.addStop(new Stop("Drum Faget"));
        as.addStop(new Stop("Centrul Medical"));
        as.addStop(new Stop("Constantin Noica"));
        as.addStop(new Stop("Meteor"));
        as.addStop(new Stop("Silviu Dragomir"));
        as.addStop(new Stop("Teatru"));

        as.addStop(new Stop("Observatorului Nord"));
        as.addStop(new Stop("Spitalul Recuperare Nord"));
        as.addStop(new Stop("Ghe. Dima"));
        as.addStop(new Stop("Frunzisului"));
        as.addStop(new Stop("Cocosul de Aur"));
        as.addStop(new Stop("Gr. Alexandrescu"));
        as.addStop(new Stop("Peana"));
        as.addStop(new Stop("Ravasului"));
        as.addStop(new Stop("Garbau"));
        as.addStop(new Stop("Clabucet"));
        as.addStop(new Stop("Bucium"));
        as.addStop(new Stop("Colina"));
        as.addStop(new Stop("Primaverii"));
        as.addStop(new Stop("Minerva"));
        as.addStop(new Stop("Izlazului"));
        as.addStop(new Stop("Frunzisului Vest"));
        as.addStop(new Stop("Varianta Zorilor"));
        as.addStop(new Stop("Zorilor"));
        as.addStop(new Stop("Spitalul Recuperare Sud"));
        as.addStop(new Stop("Observatorului Sud"));


        ae.addEmployee(new Employee("Ciobanu Vasile"));
        ae.addEmployee(new Employee("Pop Ioana"));
        ae.addEmployee(new Employee("Dobre Teodor"));
        ae.addEmployee(new Employee("Stanescu Calin"));
        ae.addEmployee(new Employee("Tabac Daniel"));
        ae.addEmployee(new Employee("Petrescu Miruna"));
        ae.addEmployee(new Employee("Moisescu Ionut"));
        ae.addEmployee(new Employee("Ursu Stefania"));
        ae.addEmployee(new Employee("Tabac Maria"));
        ae.addEmployee(new Employee("Puscasu Dan"));
        ae.addEmployee(new Employee("Mihailescu Patricia"));
        ae.addEmployee(new Employee("Rusu Ovidiu"));
        ae.addEmployee(new Employee("Ciobanu Stefana"));
        ae.addEmployee(new Employee("Constantinescu Ana"));
        ae.addEmployee(new Employee("Dobre Alexandra"));
        ae.addEmployee(new Employee("Diaconu Gheorghe"));
        ae.addEmployee(new Employee("Dobre Marian"));
        ae.addEmployee(new Employee("Lupu Daniel"));
        ae.addEmployee(new Employee("Constantinescu Paul"));
        ae.addEmployee(new Employee("Tabac Luca"));
        ae.addEmployee(new Employee("Sava Radu"));
        ae.addEmployee(new Employee("Tomescu Catalin"));
        ae.addEmployee(new Employee("Diaconu Ramona"));
        ae.addEmployee(new Employee("Fratila Iulian"));
        ae.addEmployee(new Employee("Diaconu Luca"));
        ae.addEmployee(new Employee("Munteanu Alexandru"));
        ae.addEmployee(new Employee("Mihailescu Stefan"));
        ae.addEmployee(new Employee("Dinescu Dan"));
        ae.addEmployee(new Employee("Toma Gabriela"));
        ae.addEmployee(new Employee("Stanescu Andrei"));
        ae.addEmployee(new Employee("Mocanu Ovidiu"));
        ae.addEmployee(new Employee("Cristea Gabriela"));
        ae.addEmployee(new Employee("Ciobanu Cristian"));
        ae.addEmployee(new Employee("Manole Andrei"));
        ae.addEmployee(new Employee("Puscasu Victor"));
        ae.addEmployee(new Employee("Stanescu Radu"));
        ae.addEmployee(new Employee("Nitu Ionut"));
        ae.addEmployee(new Employee("Sava Teodor"));
        ae.addEmployee(new Employee("Dinescu Catalin"));
        ae.addEmployee(new Employee("Gheorghiu Daniel"));
        ae.addEmployee(new Employee("Sava Costin"));
        ae.addEmployee(new Employee("Iancu Gheorghe"));
        ae.addEmployee(new Employee("Dinu Ovidiu"));
        ae.addEmployee(new Employee("Stanescu Marian"));
        ae.addEmployee(new Employee("Rusu Maria"));
        ae.addEmployee(new Employee("Calinescu Costin"));
        ae.addEmployee(new Employee("Florea Maria"));
        ae.addEmployee(new Employee("Nistor Daniel"));
        ae.addEmployee(new Employee("Ionita Bogdan"));
        ae.addEmployee(new Employee("Marin Daria"));
        ae.addEmployee(new Employee("Stanciu Bogdan"));
        ae.addEmployee(new Employee("Nistor Calin"));
        ae.addEmployee(new Employee("Petrescu Daria"));
        ae.addEmployee(new Employee("Mocanu Gabriel"));
        ae.addEmployee(new Employee("Sava Stefania"));
        ae.addEmployee(new Employee("Gheorghiu Ion"));
        ae.addEmployee(new Employee("Constantin Radu"));
        ae.addEmployee(new Employee("Constantin Florin"));
        ae.addEmployee(new Employee("Calinescu Ion"));
        ae.addEmployee(new Employee("Teodorescu Romana"));
        ae.addEmployee(new Employee("Munteanu Gabriel"));
        ae.addEmployee(new Employee("Tudor Paul"));
        ae.addEmployee(new Employee("Ionita Calin"));
        ae.addEmployee(new Employee("Toma Marian"));
        ae.addEmployee(new Employee("Albu Gabriel"));
        ae.addEmployee(new Employee("Dumitrescu Andreea"));
        ae.addEmployee(new Employee("Stanescu Maria"));
        ae.addEmployee(new Employee("﻿Popa Mihai"));
        ae.addEmployee(new Employee("Ionescu Ana"));
        ae.addEmployee(new Employee("Albu Ramona"));
        ae.addEmployee(new Employee("Gheorghiu Marius"));
        ae.addEmployee(new Employee("Voinea Calin"));
        ae.addEmployee(new Employee("Puscasu Ionut"));
        ae.addEmployee(new Employee("Ionita Ana"));
        ae.addEmployee(new Employee("Nita Mihai"));
        ae.addEmployee(new Employee("Toma Victor"));
        ae.addEmployee(new Employee("Mehedintu Cristian"));
        ae.addEmployee(new Employee("Mehedintu Cristian"));
        ae.addEmployee(new Employee("Voinea Ionut"));
        ae.addEmployee(new Employee("Stanescu Calin"));
        ae.addEmployee(new Employee("Toma Tudor"));
        ae.addEmployee(new Employee("Nistor Ana"));
        ae.addEmployee(new Employee("Dinescu Costin"));
        ae.addEmployee(new Employee("Ciobanu Catalin"));
        ae.addEmployee(new Employee("Teodorescu Florin"));
        ae.addEmployee(new Employee("Calinescu Paul"));
        ae.addEmployee(new Employee("Rusu Luca"));
        ae.addEmployee(new Employee("Nistor Luca"));
        ae.addEmployee(new Employee("Dumitrescu Florin"));
        ae.addEmployee(new Employee("Toma Stefania"));
        ae.addEmployee(new Employee("Pop Catalin"));
        ae.addEmployee(new Employee("Toma Alexandra"));
        ae.addEmployee(new Employee("Nistor Ion"));
        ae.addEmployee(new Employee("Voinea Ovidiu"));
        ae.addEmployee(new Employee("Florea Ioana"));
        ae.addEmployee(new Employee("Ciobanu Ana"));
        ae.addEmployee(new Employee("Constantin Ovidiu"));
        ae.addEmployee(new Employee("Teodorescu Alexandru"));
        ae.addEmployee(new Employee("Munteanu Ramona"));
        ae.addEmployee(new Employee("Lupu Vasile"));
        ae.addEmployee(new Employee("Munteanu Iulian"));
        ae.addEmployee(new Employee("Petrescu Victor"));
        ae.addEmployee(new Employee("Andreescu Ioana"));
        ae.addEmployee(new Employee("Nita Marian"));
        ae.addEmployee(new Employee("Teodorescu Andreea"));
        ae.addEmployee(new Employee("Dinu Daria"));
        ae.addEmployee(new Employee("Popescu Teodor"));
        ae.addEmployee(new Employee("Petrescu Elena"));
        ae.addEmployee(new Employee("Gheorghiu Romana"));
        ae.addEmployee(new Employee("Nitu Maria"));
        ae.addEmployee(new Employee("Andreescu Victor"));
        ae.addEmployee(new Employee("Georgescu Stefania"));
        ae.addEmployee(new Employee("Rusu Stefan"));
        ae.addEmployee(new Employee("Blaga Stefana"));
        ae.addEmployee(new Employee("Pop Stefana"));
        ae.addEmployee(new Employee("Constantinescu Gabriela"));
        ae.addEmployee(new Employee("Lupu David"));
        ae.addEmployee(new Employee("Mehedintu Ana"));
        ae.addEmployee(new Employee("Constantinescu Florin"));
        ae.addEmployee(new Employee("Marin Ramona"));
        ae.addEmployee(new Employee("Diaconescu Stefan"));
        ae.addEmployee(new Employee("Dobre Costin"));
        ae.addEmployee(new Employee("Diaconescu Cristian"));
        ae.addEmployee(new Employee("Nistor Daniel"));
        ae.addEmployee(new Employee("Sava Ramona"));
        ae.addEmployee(new Employee("Ciobanu Cristian"));
        ae.addEmployee(new Employee("Tabac Ovidiu"));
        ae.addEmployee(new Employee("Dobre Miruna"));
        ae.addEmployee(new Employee("Andreescu Teodor"));
        ae.addEmployee(new Employee("Mocanu Daniel"));
        ae.addEmployee(new Employee("Dima Gheorghe"));
        ae.addEmployee(new Employee("Albu Marian"));
        ae.addEmployee(new Employee("Dinescu Paul"));
        ae.addEmployee(new Employee("Mehedintu Gabriel"));
        ae.addEmployee(new Employee("Popescu Cristian"));
        ae.addEmployee(new Employee("Toma Andrei"));
        ae.addEmployee(new Employee("Ciobanu Andreea"));
        ae.addEmployee(new Employee("Sava Costin"));
        ae.addEmployee(new Employee("Stanciu Alexandru"));
        ae.addEmployee(new Employee("Nistor Daria"));
        ae.addEmployee(new Employee("Teodoru Tudor"));
        ae.addEmployee(new Employee("Dinescu Stefana"));
        ae.addEmployee(new Employee("Munteanu Bogdan"));
        ae.addEmployee(new Employee("Dima Ana"));
        ae.addEmployee(new Employee("Popescu Ovidiu"));
        ae.addEmployee(new Employee("Diaconu Victor"));
        ae.addEmployee(new Employee("Fratila Alexandra"));
        ae.addEmployee(new Employee("Petrescu Mihai"));
        ae.addEmployee(new Employee("Manole Iulian"));
        ae.addEmployee(new Employee("Tudor Paul"));


        vp.addVehicle(new Vehicle(100, 123, Vehicle.vehicleType.BUS));
        vp.addVehicle(new Vehicle(100, 845, Vehicle.vehicleType.BUS));
        vp.addVehicle(new Vehicle(100, 756, Vehicle.vehicleType.BUS));
        vp.addVehicle(new Vehicle(100, 231, Vehicle.vehicleType.BUS));

        r1.addStop(as.getStop(2));
        r1.addStop(as.getStop(1));
        r1.addStop(as.getStop(0));

        r2.addStop(as.getStop(0));
        r2.addStop(as.getStop(5));
        r2.addStop(as.getStop(4));
        r2.addStop(as.getStop(3));

        ar.addRoute(r1);
        ar.addRoute(r2);

        MainFrame mf = new MainFrame(vp, ar, as, ae, d1, d2, d3);
        TimeControlFrame tcf = new TimeControlFrame(mf);
    }
}
